.PHONY: all clean

all:
	$(MAKE) -C 1task
	$(MAKE) -C 2task
	$(MAKE) -C 3task
	$(MAKE) -C 4task
	$(MAKE) -C 5task
	$(MAKE) -C 6task
	$(MAKE) -C 7task
	$(MAKE) -C 8task

clean:
	$(MAKE) -C 1task clean
	$(MAKE) -C 2task clean
	$(MAKE) -C 3task clean
	$(MAKE) -C 4task clean
	$(MAKE) -C 5task clean
	$(MAKE) -C 6task clean
	$(MAKE) -C 7task clean
	$(MAKE) -C 8task clean